
PROJ_NAME = Sudoku

SRC = src\main.c\
src\printSudoku.c\
src\inputSudoku.c\
src\safeSudoku.c\
src\solveSudoku.c

INC = inc

#$(PROJ_NAME) : $(SRC)
#	gcc -I $(INC) $(SRC) -o $(PROJ_NAME).exe

#run : $(PROJ_NAME)
#	$(PROJ_NAME)

#clean: del /q *.exe